
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: CVE-2023-40477 Potential Exploitation - WinRAR Application Crash
id: e5a29b54-6fe7-4258-8a23-82960e31231a
status: experimental
description: Detects a crash of "WinRAR.exe" where the version is lower than 6.23.
    This could indicate potential exploitation of CVE-2023-40477
author: Nasreddine Bencherchali (Nextron Systems)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2023/08/31 21:00:21
references:
  - https://wildptr.io/winrar-cve-2023-40477-poc-new-vulnerability-winrar-security-research/
  - https://github.com/wildptr-io/Winrar-CVE-2023-40477-POC
  - https://www.rarlab.com/vuln_rev3_names.html
logsource:
    product: windows
    service: application
detection:
    condition: selection and not 1 of filter_main_*
    filter_main_fixed_version:
        AppVersion|startswith:
          - 6.23.
          - 6.24.
          - 6.25.
          - 6.26.
          - "7."
    selection:
        AppName: WinRAR.exe
        EventID: "1000"
        Provider_Name: Application Error
falsepositives: Legitimate crash for reasons other than exploitation of the vulnerability
level: medium
customer: 'demo'
tags:
  - attack.execution
  - cve.2023.40477
  - detection.emerging_threats
  - DEMO
