
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Using SettingSyncHost.exe as LOLBin
id: b2ddd389-f676-4ac4-845a-e00781a48e5f
status: test
description: Detects using SettingSyncHost.exe to run hijacked binary
author: Anton Kutepov, oscd.community
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2020/02/05 15:04:31
references:
  - https://www.hexacorn.com/blog/2020/02/02/settingsynchost-exe-as-a-lolbin
logsource:
    category: process_creation
    product: windows
detection:
    condition: not system_utility and parent_is_settingsynchost
    parent_is_settingsynchost:
        ParentCommandLine|contains|all:
          - cmd.exe /c
          - RoamDiag.cmd
          - -outputpath
    system_utility:
        Image|startswith:
          - C:\Windows\System32\
          - C:\Windows\SysWOW64\
fields:
  - TargetFilename
  - Image
falsepositives: Unknown
level: high
customer: 'demo'
modified: 2021/11/27
tags:
  - attack.execution
  - attack.defense_evasion
  - attack.t1574.008
  - DEMO
