
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Application Removed Via Wmic.EXE
id: b53317a0-8acf-4fd1-8de8-a5401e776b96
related:
  - type: derived
    id: 847d5ff3-8a31-4737-a970-aeae8fe21765
status: test
description: Uninstall an application with wmic
author: frack113
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2022/01/28 14:06:21
references:
  - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
logsource:
    category: process_creation
    product: windows
detection:
    condition: all of selection_*
    selection_cli:
        CommandLine|contains:
          - call
          - uninstall
    selection_img:
      - Image|endswith: \WMIC.exe
      - OriginalFileName: wmic.exe
falsepositives: Unknown
level: medium
customer: 'demo'
modified: 2023/02/14
tags:
  - attack.execution
  - attack.t1047
  - DEMO
