
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: UAC Bypass Using MSConfig Token Modification - Process
id: ad92e3f9-7eb6-460e-96b1-582b0ccbb980
status: test
description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
author: Christian Burkard (Nextron Systems)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2021/08/30 19:32:21
references:
  - https://github.com/hfiref0x/UACME
logsource:
    category: process_creation
    product: windows
detection:
    condition: selection
    selection:
        CommandLine: '"C:\Windows\system32\msconfig.exe" -5'
        IntegrityLevel:
          - High
          - System
        ParentImage|endswith: \AppData\Local\Temp\pkgmgr.exe
falsepositives: Unknown
level: high
customer: 'demo'
modified: 2022/10/09
tags:
  - attack.defense_evasion
  - attack.privilege_escalation
  - attack.t1548.002
  - DEMO
