
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: HackTool - RedMimicry Winnti Playbook Execution
id: 95022b85-ff2a-49fa-939a-d7b8f56eeb9b
status: test
description: Detects actions caused by the RedMimicry Winnti playbook a automated
    breach emulations utility
author: Alexander Rausch
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2020/06/24 18:16:51
references:
  - https://redmimicry.com/posts/redmimicry-winnti/
logsource:
    category: process_creation
    product: windows
detection:
    condition: selection
    selection:
        CommandLine|contains:
          - gthread-3.6.dll
          - \Windows\Temp\tmp.bat
          - sigcmm-2.4.dll
        Image|endswith:
          - \rundll32.exe
          - \cmd.exe
falsepositives: Unknown
level: high
customer: 'demo'
modified: 2023/03/01
tags:
  - attack.execution
  - attack.defense_evasion
  - attack.t1106
  - attack.t1059.003
  - attack.t1218.011
  - DEMO
