
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Suspicious ConfigSecurityPolicy Execution
id: 1f0f6176-6482-4027-b151-00071af39d7e
status: test
description: Upload file, credentials or data exfiltration with Binary part of Windows
    Defender
author: frack113
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2021/11/26 17:34:51
references:
  - https://lolbas-project.github.io/lolbas/Binaries/ConfigSecurityPolicy/
logsource:
    category: process_creation
    product: windows
detection:
    condition: lolbas and remote
    lolbas:
      - CommandLine|contains: ConfigSecurityPolicy.exe
      - Image|endswith: \ConfigSecurityPolicy.exe
      - OriginalFileName: ConfigSecurityPolicy.exe
    remote:
        CommandLine|contains:
          - https://
          - http://
          - ftp://
falsepositives: Unknown
level: medium
customer: 'demo'
modified: 2022/05/16
tags:
  - attack.exfiltration
  - attack.t1567
  - DEMO
