
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-06-21 19:00
# Generated for User: demo
# Number of Rules: 3228
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Arbitrary File Download Via ConfigSecurityPolicy.EXE
id: 1f0f6176-6482-4027-b151-00071af39d7e
status: test
description: |
    Detects the execution of "ConfigSecurityPolicy.EXE", a binary part of Windows Defender used to manage settings in Windows Defender.
    Users can configure different pilot collections for each of the co-management workloads.
    It can be abused by attackers in order to upload or download files.
author: frack113
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2021/11/26 19:39:41
references:
  - https://lolbas-project.github.io/lolbas/Binaries/ConfigSecurityPolicy/
logsource:
    category: process_creation
    product: windows
detection:
    condition: all of selection_*
    selection_img:
      - CommandLine|contains: ConfigSecurityPolicy.exe
      - Image|endswith: \ConfigSecurityPolicy.exe
      - OriginalFileName: ConfigSecurityPolicy.exe
    selection_url:
        CommandLine|contains:
          - ftp://
          - http://
          - https://
falsepositives: Unknown
level: medium
customer: 'demo'
modified: 2022/05/16
tags:
  - attack.exfiltration
  - attack.t1567
  - DEMO
