
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Sysmon Configuration Update
id: 87911521-7098-470b-a459-9a57fc80bdfd
status: test
description: Detects updates to Sysmon's configuration. Attackers might update or
    replace the Sysmon configuration with a bare bone one to avoid monitoring without
    shutting down the service completely
author: Nasreddine Bencherchali (Nextron Systems)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2023/03/09 13:28:41
references:
  - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
logsource:
    category: process_creation
    product: windows
detection:
    condition: all of selection_*
    selection_cli:
        CommandLine|contains|windash: -c
    selection_pe:
      - Image|endswith:
          - \Sysmon64.exe
          - \Sysmon.exe
      - Description: System activity monitor
falsepositives: Legitimate administrators might use this command to update Sysmon
    configuration.
level: medium
customer: 'demo'
modified: 2024/03/13
tags:
  - attack.defense_evasion
  - attack.t1562.001
  - DEMO
