
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-06-21 19:00
# Generated for User: demo
# Number of Rules: 3228
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Kubernetes Secrets Enumeration
id: eeb3e9e1-b685-44e4-9232-6bb701f925b5
related:
  - type: derived
    id: 7ee0b4aa-d8d4-4088-b661-20efdf41a04c
status: experimental
description: Detects enumeration of Kubernetes secrets.
author: Leo Tsaousis (@laripping)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2024/03/26 14:20:01
references:
  - https://microsoft.github.io/Threat-Matrix-for-Kubernetes/techniques/List%20K8S%20secrets/
logsource:
    category: application
    product: kubernetes
    service: audit
detection:
    condition: selection
    selection:
        objectRef.resource: secrets
        verb: list
falsepositives: The Kubernetes dashboard occasionally accesses the kubernetes-dashboard-key-holder
    secret
level: low
customer: 'demo'
tags:
  - attack.t1552.007
  - DEMO
