
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-06-21 19:00
# Generated for User: demo
# Number of Rules: 3228
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: New Kubernetes Service Account Created
id: e31bae15-83ed-473e-bf31-faf4f8a17d36
related:
  - type: derived
    id: 12d027c3-b48c-4d9d-8bb6-a732200034b2
status: experimental
description: |
    Detects creation of new Kubernetes service account, which could indicate an attacker's attempt to persist within a cluster.
author: Leo Tsaousis (@laripping)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2024/03/26 16:01:21
references:
  - https://microsoft.github.io/Threat-Matrix-for-Kubernetes/techniques/container%20service%20account/
logsource:
    category: application
    product: kubernetes
    service: audit
detection:
    condition: selection
    selection:
        objectRef.resource: serviceaccounts
        verb: create
falsepositives: Unknown
level: low
customer: 'demo'
tags:
  - attack.t1136
  - DEMO
