
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-06-21 19:00
# Generated for User: demo
# Number of Rules: 3228
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Potential Remote Command Execution In Pod Container
id: a1b0ca4e-7835-413e-8471-3ff2b8a66be6
status: experimental
description: |
    Detects attempts to execute remote commands, within a Pod's container using e.g. the "kubectl exec" command.
author: Leo Tsaousis (@laripping)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2024/03/26 19:22:01
references:
  - https://microsoft.github.io/Threat-Matrix-for-Kubernetes/techniques/Exec%20into%20container/
logsource:
    category: application
    product: kubernetes
    service: audit
detection:
    condition: selection
    selection:
        objectRef.resource: pods
        objectRef.subresource: exec
        verb: create
falsepositives: Legitimate debugging activity. Investigate the identity performing
    the requests and their authorization.
level: medium
customer: 'demo'
tags:
  - attack.t1609
  - DEMO
