
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-06-21 19:00
# Generated for User: demo
# Number of Rules: 3228
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Container With A hostPath Mount Created
id: 402b955c-8fe0-4a8c-b635-622b4ac5f902
status: experimental
description: |
    Detects creation of a container with a hostPath mount.
    A hostPath volume mounts a directory or a file from the node to the container.
    Attackers who have permissions to create a new pod in the cluster may create one with a writable hostPath volume and chroot to escape to the underlying node.
author: Leo Tsaousis (@laripping)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2024/03/26 16:06:21
references:
  - https://microsoft.github.io/Threat-Matrix-for-Kubernetes/techniques/Writable%20hostPath%20mount/
  - https://blog.appsecco.com/kubernetes-namespace-breakout-using-insecure-host-path-volume-part-1-b382f2a6e216
logsource:
    category: application
    product: kubernetes
    service: audit
detection:
    condition: selection
    selection:
        hostPath: '*'
        objectRef.resource: pods
        verb: create
falsepositives: The DaemonSet controller creates pods with hostPath volumes within
    the kube-system namespace.
level: low
customer: 'demo'
tags:
  - attack.t1611
  - DEMO
