
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-06-21 19:00
# Generated for User: demo
# Number of Rules: 3228
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Creation Of Pod In System Namespace
id: a80d927d-ac6e-443f-a867-e8d6e3897318
status: experimental
description: |
    Detects deployments of pods within the kube-system namespace, which could be intended to imitate system pods.
    System pods, created by controllers such as Deployments or DaemonSets have random suffixes in their names.
    Attackers can use this fact and name their backdoor pods as if they were created by these controllers to avoid detection.
    Deployment of such a backdoor container e.g. named kube-proxy-bv61v, could be attempted in the kube-system namespace alongside the other administrative containers.
author: Leo Tsaousis (@laripping)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2024/03/26 14:51:41
references:
  - https://microsoft.github.io/Threat-Matrix-for-Kubernetes/techniques/Pod%20or%20container%20name%20similarily/
logsource:
    category: application
    product: kubernetes
    service: audit
detection:
    condition: selection
    selection:
        objectRef.namespace: kube-system
        objectRef.resource: pods
        verb: create
falsepositives: System components such as daemon-set-controller and kube-scheduler
    also create pods in the kube-system namespace
level: medium
customer: 'demo'
tags:
  - attack.t1036.005
  - DEMO
