
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-07 01:36
# Generated for User: demo
# Number of Rules: 3139
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Azure Device or Configuration Modified or Deleted
id: 46530378-f9db-4af9-a9e5-889c177d3881
status: test
description: Identifies when a device or device configuration in azure is modified
    or deleted.
author: Austin Songer @austinsonger
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2021/09/03 18:49:31
references:
  - https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/reference-audit-activities#core-directory
logsource:
    product: azure
    service: activitylogs
detection:
    condition: selection
    selection:
        properties.message:
          - Delete device
          - Delete device configuration
          - Update device
          - Update device configuration
falsepositives:
  - Device or device configuration being modified or deleted may be performed by a
    system administrator.
  - Verify whether the user identity, user agent, and/or hostname should be making
    changes in your environment.
  - Device or device configuration modified or deleted from unfamiliar users should
    be investigated. If known behavior is causing false positives, it can be exempted
    from the rule.
level: medium
customer: 'demo'
modified: 2022/10/09
tags:
  - attack.impact
  - attack.t1485
  - attack.t1565.001
  - DEMO
