
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-07 01:36
# Generated for User: demo
# Number of Rules: 3139
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Azure Kubernetes Secret or Config Object Access
id: 7ee0b4aa-d8d4-4088-b661-20efdf41a04c
status: test
description: Identifies when a Kubernetes account access a sensitive objects such
    as configmaps or secrets.
author: Austin Songer @austinsonger
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2021/08/07 18:11:31
references:
  - https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftkubernetes
  - https://www.microsoft.com/security/blog/2021/03/23/secure-containerized-environments-with-updated-threat-matrix-for-kubernetes/
  - https://www.microsoft.com/security/blog/2020/04/02/attack-matrix-kubernetes/
  - https://medium.com/mitre-engenuity/att-ck-for-containers-now-available-4c2359654bf1
  - https://attack.mitre.org/matrices/enterprise/cloud/
logsource:
    product: azure
    service: activitylogs
detection:
    condition: selection
    selection:
        operationName:
          - MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/CONFIGMAPS/WRITE
          - MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/CONFIGMAPS/DELETE
          - MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SECRETS/WRITE
          - MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SECRETS/DELETE
falsepositives: Sensitive objects may be accessed by a system administrator. Verify
    whether the user identity, user agent, and/or hostname should be making changes
    in your environment. Sensitive objects accessed from unfamiliar users should be
    investigated. If known behavior is causing false positives, it can be exempted
    from the rule.
level: medium
customer: 'demo'
modified: 2022/08/23
tags:
  - attack.impact
  - DEMO
