title: Potential Suspicious Changes To Windows Update Settings
id: 83954e69-b883-4c7b-a3d6-0d113a5f2cad
status: experimental
description: |
    Detects suspicious changes to Windows Update registry settings such as "Disabling Auto Updates" or "Auto Installs".
    While these changes are not malicious by nature on servers (see false positive section), seeing these changes on endpoint systems can be indicative of suspicious activity.
references:
    - https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::DoNotConnectToWindowsUpdateInternetLocations
    - https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::ImmediateInstall_Title
    - https://admx.help/?Category=Windows_8.1_2012R2&Policy=Microsoft.Policies.WindowsUpdate::CorpWuURL
    - https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::NoAutoRebootWithLoggedOnUsers_Title
    - https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsUpdate::AutoUpdateCfg
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/03/17
tags:
    - attack.defense_evasion
logsource:
    product: windows
    category: registry_set
detection:
    selection_auoptions:
        EventType: SetValue
        TargetObject|contains: '\Microsoft\Windows\WindowsUpdate\AU\AUOptions'
        Details: 'DWORD (0x00000002)' # Only notify before downloading and installing any updates.
    selection_auto_install_minor_updates:
        EventType: SetValue
        TargetObject|contains: '\Microsoft\Windows\WindowsUpdate\AU\AutoInstallMinorUpdates'
        Details: 'DWORD (0x00000000)' # Disable "Allow Automatic Updates immediate installation"
    selection_no_auto_update:
        EventType: SetValue
        TargetObject|contains: '\Microsoft\Windows\WindowsUpdate\AU\NoAutoUpdate'
        Details: 'DWORD (0x00000001)' # Disable "Auto Updates"
    selection_no_auto_reboot:
        EventType: SetValue
        TargetObject|contains:
            - '\Microsoft\Windows\WindowsUpdate\AU\NoAutoRebootWithLoggedOnUsers'
            - '\Microsoft\Windows\WindowsUpdate\NoAutoRebootWithLoggedOnUsers'
        Details: 'DWORD (0x00000001)' # Disable "auto-restart with logged on users for scheduled automatic updates"
    condition: 1 of selection_*
falsepositives:
    - False positives are expected in organizations that levreage an internal WSUS server or have critical servers that they don't want rebooted.
level: medium
