
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Windows Defender Exploit Guard Tamper
id: a3ab73f1-bd46-4319-8f06-4b20d0617886
status: test
description: |
    Detects when someone is adding or removing applications or folders from exploit guard "ProtectedFolders" or "AllowedApplications"
author: Nasreddine Bencherchali (Nextron Systems)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2022/08/05 15:48:11
references:
  - https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/windows-10-controlled-folder-access-event-search/ba-p/2326088
logsource:
    product: windows
    service: windefend
detection:
    condition: all of allowed_apps* or protected_folders
    allowed_apps_key:
        EventID: "5007"
        NewValue|contains: \Windows Defender\Windows Defender Exploit Guard\Controlled
            Folder Access\AllowedApplications\
    allowed_apps_path:
        NewValue|contains:
          - \Users\Public\
          - \AppData\Local\Temp\
          - \Desktop\
          - \PerfLogs\
          - \Windows\Temp\
    protected_folders:
        EventID: "5007"
        OldValue|contains: \Windows Defender\Windows Defender Exploit Guard\Controlled
            Folder Access\ProtectedFolders\
falsepositives: Unlikely
level: high
customer: 'demo'
modified: 2022/12/06
tags:
  - attack.defense_evasion
  - attack.t1562.001
  - DEMO
