
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-07 01:36
# Generated for User: demo
# Number of Rules: 3139
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: DHCP Server Error Failed Loading the CallOut DLL
id: 75edd3fd-7146-48e5-9848-3013d7f0282c
status: test
description: This rule detects a DHCP server error in which a specified Callout DLL
    (in registry) could not be loaded
author: Dimitrios Slamaris, @atc_project (fix)
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2017/05/15 17:36:41
references:
  - https://blog.3or.de/mimilib-dhcp-server-callout-dll-injection.html
  - https://technet.microsoft.com/en-us/library/cc726884(v=ws.10).aspx
  - https://msdn.microsoft.com/de-de/library/windows/desktop/aa363389(v=vs.85).aspx
logsource:
    product: windows
    service: system
detection:
    condition: selection
    selection:
        EventID:
          - "1031"
          - "1032"
          - "1034"
        Provider_Name: Microsoft-Windows-DHCP-Server
falsepositives: Unknown
level: high
customer: 'demo'
modified: 2022/12/25
tags:
  - attack.defense_evasion
  - attack.t1574.002
  - DEMO
