
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: ADCS Certificate Template Configuration Vulnerability with Risky EKU
id: bfbd3291-de87-4b7c-88a2-d6a5deb28668
status: test
description: Detects certificate creation with template allowing risk permission subject
    and risky EKU
author: Orlinum , BlueDefenZer
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2021/11/17 23:49:11
references:
  - https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
logsource:
    product: windows
    service: security
    definition: Certificate services loaded a template would trigger event ID 4898
        and certificate Services template was updated would trigger event ID 4899.
        A risk permission seems to be coming if template contain specific flag with
        risky EKU.
detection:
    condition: (selection10 and selection11) or (selection20 and selection21)
    selection10:
        EventID: "4898"
        TemplateContent|contains:
          - 1.3.6.1.5.5.7.3.2
          - 1.3.6.1.5.2.3.4
          - 1.3.6.1.4.1.311.20.2.2
          - 2.5.29.37.0
    selection11:
        TemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    selection20:
        EventID: "4899"
        NewTemplateContent|contains:
          - 1.3.6.1.5.5.7.3.2
          - 1.3.6.1.5.2.3.4
          - 1.3.6.1.4.1.311.20.2.2
          - 2.5.29.37.0
    selection21:
        NewTemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
falsepositives:
  - Administrator activity
  - Proxy SSL certificate with subject modification
  - Smart card enrollement
level: high
customer: 'demo'
modified: 2022/12/25
tags:
  - attack.privilege_escalation
  - attack.credential_access
  - DEMO
