
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Azure Owner Removed From Application or Service Principal
id: 636e30d5-3736-42ea-96b1-e6e2f8429fd6
status: test
description: Identifies when a owner is was removed from a application or service
    principal in Azure.
author: Austin Songer @austinsonger
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2021/09/03 21:01:21
references:
  - https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/reference-audit-activities#application-proxy
logsource:
    product: azure
    service: activitylogs
detection:
    condition: selection
    selection:
        properties.message:
          - Remove owner from service principal
          - Remove owner from application
falsepositives:
  - Owner being removed may be performed by a system administrator.
  - Verify whether the user identity, user agent, and/or hostname should be making
    changes in your environment.
  - Owner removed from unfamiliar users should be investigated. If known behavior
    is causing false positives, it can be exempted from the rule.
level: medium
customer: 'demo'
modified: 2022/10/09
tags:
  - attack.defense_evasion
  - DEMO
