
# VALHALLA SIGMA RULE SET - DEMO
# Retrieved: 2024-03-26 18:48
# Generated for User: demo
# Number of Rules: 3189
# Warning:
#     The full rule set contains rules with low level (< high) 
#     that can lead to false positives - use the Python
#     module valhallaAPI tools to retrieve a filtered set
# This is the VALHALLA demo rule set. The content represents the 'SigmaHQ' repository
# in a streamlined format.
# All rules are licensed under DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md.
title: Outlook Security Settings Updated - Registry
id: c3cefdf4-6703-4e1c-bad8-bf422fc5015a
related:
  - type: similar
    id: a166f74e-bf44-409d-b9ba-ea4b2dd8b3cd
status: test
description: Detects changes to the registry values related to outlook security settings
author: frack113
license: 'DRL 1.1 https://github.com/SigmaHQ/sigma/blob/master/LICENSE.Detection.Rules.md'
date: 2021/12/28 17:44:31
references:
  - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1137/T1137.md
  - https://docs.microsoft.com/en-us/outlook/troubleshoot/security/information-about-email-security-settings
logsource:
    category: registry_set
    product: windows
detection:
    condition: selection
    selection:
        TargetObject|contains|all:
          - \SOFTWARE\Microsoft\Office\
          - \Outlook\Security\
falsepositives: Administrative activity
level: medium
customer: 'demo'
modified: 2023/08/17
tags:
  - attack.persistence
  - attack.t1137
  - DEMO
